#!/bin/sh

KEYFILE=keyfile

IMAGE=mongo:4-bionic
NAME=mongo
PORT=27017

HOST_DIR="`pwd`/data/db"
GUEST_DIR=/data/db
RS_NAME=rs

ID=999

mkdir -p $HOST_DIR || true
sudo chown $ID $HOST_DIR

docker stop $NAME
docker rm $NAME
docker run \
  --restart unless-stopped \
  --detach \
  --name $NAME \
  --publish 0.0.0.0:$PORT:$PORT \
  --volume "`pwd`/$KEYFILE:/data/$KEYFILE" \
  --volume "$HOST_DIR:$GUEST_DIR" \
  $IMAGE \
    --auth \
    --replSet $RS_NAME \
    --keyFile "/data/$KEYFILE"
docker ps
