#!/bin/sh

NAME=mongo

USER_NAME=admin

rs_init=$(cat <<-END

  use admin;
  db.createUser({ user: "$USER_NAME", pwd: passwordPrompt(), roles: ["root"] });

END
)

echo "$rs_init"

echo ""
echo "[openssl rand -base64 32]"
echo ""
echo "  `openssl rand -base64 32`"
echo "  `openssl rand -base64 32`"
echo "  `openssl rand -base64 32`"
echo "  `openssl rand -base64 32`"
echo "  `openssl rand -base64 32`"
echo ""
docker exec -it $NAME mongo --host localhost
