#!/bin/sh

if [ $# -ne 5  ]; then
  echo usage: $0 ip0 ip1 ip2 user_name db_name
  exit 1
fi

RS_NAME=rs
ip0=$1
ip1=$2
ip2=$3
admin_name=admin
user_name=$4
db_name=$5

IMAGE=mongo:4-bionic

eval=$(cat <<-END

  use $db_name;
  db.createUser({ user: "$user_name", pwd: passwordPrompt(), roles: [ { role: "readWrite", db: "$db_name" } ] });

END
)

echo "$eval"

echo ""
echo "[openssl rand -base64 32]"
echo ""
echo "  `openssl rand -base64 32`"
echo "  `openssl rand -base64 32`"
echo "  `openssl rand -base64 32`"
echo "  `openssl rand -base64 32`"
echo "  `openssl rand -base64 32`"
echo ""

docker run \
  --add-host db0:$ip0 \
  --add-host db1:$ip1 \
  --add-host db2:$ip2 \
  -it \
  --rm \
  $IMAGE \
  /bin/bash -c "mkdir /home/mongodb && touch /home/mongodb/.dbshell && mongo --username $admin_name --host $RS_NAME/db0,db1,db2 --password"
