#!/bin/sh
if [ $# -ne 3  ]; then
  echo usage: $0 ip0 ip1 ip2
  exit 1
fi

NAME=mongo

RS_NAME=rs
ip0=$1
ip1=$2
ip2=$3

rs_init=$(cat <<-END
  var cfg = {
    "_id": "$RS_NAME",
    "version": 1,
    "members": [
      { "_id": 0, "host": "$ip0:27017", "priority": 2 },
      { "_id": 1, "host": "$ip1:27017", "priority": 0 },
      { "_id": 2, "host": "$ip2:27017", "priority": 0 }
    ]
  };
  rs.initiate(cfg, { force: true });
  // rs.reconfig(cfg, { force: true });
  // db.getMongo().setReadPref('nearest');
END
)

echo "$rs_init"

docker exec -it $NAME mongo --host localhost --eval "$rs_init"
