#!/bin/sh

if [ $# -ne 2  ]; then
  echo usage: $0 device_id mount_path
  exit 1
fi

device_id=$1 # sdb
mount_path=$2 # /var/lib/mongodb /data/btc

lsblk
sudo mkfs.ext4 -T news /dev/$device_id
sudo mkdir -p $mount_path
sudo mount -o discard,defaults /dev/$device_id $mount_path

sudo chmod 755 $mount_path
sudo chown 999 $mount_path

# fstab...
blkid | grep $device_id
lsblk
